ColWidths_connform.ListSessions<|||>1<|||>163,50,50,50,50,50,10
ColsVisible_connform.ListSessions<|||>1<|||>0,1,4,6
ColPositions_connform.ListSessions<|||>1<|||>0,1,2,3,4,5,6
ColSort_connform.ListSessions<|||>1<|||>0,0
MainWinOnMonitor<|||>3<|||>0
MainWinWidth<|||>3<|||>993
MainWinHeight<|||>3<|||>525
ColWidths_MainForm.ListDatabases<|||>1<|||>150,80,50,50,50,50,50,50,50,50,120
ColsVisible_MainForm.ListDatabases<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10
ColPositions_MainForm.ListDatabases<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10
ColSort_MainForm.ListDatabases<|||>1<|||>0,0
ColWidths_MainForm.ListVariables<|||>1<|||>160,200,428
ColsVisible_MainForm.ListVariables<|||>1<|||>0,1,2
ColPositions_MainForm.ListVariables<|||>1<|||>0,1,2
ColSort_MainForm.ListVariables<|||>1<|||>0,0
ColWidths_MainForm.ListStatus<|||>1<|||>160,428,100,100
ColsVisible_MainForm.ListStatus<|||>1<|||>0,1,2,3
ColPositions_MainForm.ListStatus<|||>1<|||>0,1,2,3
ColSort_MainForm.ListStatus<|||>1<|||>0,0
ColWidths_MainForm.ListProcesses<|||>1<|||>70,80,80,80,80,50,50,298
ColsVisible_MainForm.ListProcesses<|||>1<|||>0,1,2,3,4,5,6,7
ColPositions_MainForm.ListProcesses<|||>1<|||>0,1,2,3,4,5,6,7
ColSort_MainForm.ListProcesses<|||>1<|||>0,1
ColWidths_MainForm.ListCommandStats<|||>1<|||>120,100,100,100,368
ColsVisible_MainForm.ListCommandStats<|||>1<|||>0,1,2,3,4
ColPositions_MainForm.ListCommandStats<|||>1<|||>0,1,2,3,4
ColSort_MainForm.ListCommandStats<|||>1<|||>1,1
ColWidths_MainForm.ListTables<|||>1<|||>120,70,70,120,120,70,100,50,70,70,70,70,70,90,120,70,70,70,50
ColsVisible_MainForm.ListTables<|||>1<|||>0,1,2,3,4,5,6,18
ColPositions_MainForm.ListTables<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
ColSort_MainForm.ListTables<|||>1<|||>0,0
Updatecheck<|||>3<|||>1
DoUsageStatistics<|||>3<|||>1
UpdatecheckLastrun<|||>1<|||>2022-11-09 10:37:09
LastUsageStatisticCall<|||>1<|||>2022-11-09 10:37:10
LastSessions<|||>1<|||>Unnamed
LastActiveSession<|||>1<|||>Unnamed
SessionManager_WindowLeft<|||>3<|||>574
SessionManager_WindowTop<|||>3<|||>160
ColWidths_frmTableEditor.listColumns<|||>1<|||>42,100,154,90,60,65,50,117,130,140,100,100
ColsVisible_frmTableEditor.listColumns<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10,11
ColPositions_frmTableEditor.listColumns<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10,11
ColSort_frmTableEditor.listColumns<|||>1<|||>-1,0
ColWidths_frmTableEditor.treeIndexes<|||>1<|||>311,100,80,120
ColsVisible_frmTableEditor.treeIndexes<|||>1<|||>0,1,2,3
ColPositions_frmTableEditor.treeIndexes<|||>1<|||>0,1,2,3
ColSort_frmTableEditor.treeIndexes<|||>1<|||>-1,0
ColWidths_frmTableEditor.listForeignKeys<|||>1<|||>197,80,100,80,80,80
ColsVisible_frmTableEditor.listForeignKeys<|||>1<|||>0,1,2,3,4,5
ColPositions_frmTableEditor.listForeignKeys<|||>1<|||>0,1,2,3,4,5
ColSort_frmTableEditor.listForeignKeys<|||>1<|||>-1,0
ColWidths_frmTableEditor.listCheckConstraints<|||>1<|||>200,417
ColsVisible_frmTableEditor.listCheckConstraints<|||>1<|||>0,1
ColPositions_frmTableEditor.listCheckConstraints<|||>1<|||>0,1
ColSort_frmTableEditor.listCheckConstraints<|||>1<|||>-1,0
MainWinMaximized<|||>3<|||>1
ExportSQL_CreateDatabases<|||>3<|||>1
ExportSQL_CreateTables<|||>3<|||>1
ExportSQL_Filenames<|||>1<|||>C:\Users\USUARIO\Desktop\compañerosporsimilitud.sql<{{{><}}}>D:\Documentos\Ingeniería de sistemas\Asignaturas\Lenguaje web l\Eclipse\workspace\Lovely\lovely.sql<{{{><}}}>D:\Documentos\Ingeniería de sistemas\Asignaturas\Lenguaje web l\Eclipse\workspace\Productos\Producto.sql<{{{><}}}>D:\Documentos\Ingeniería de sistemas\Asignaturas\Ingeniería de Software lll\compañerosPorSimilitud.sql<{{{><}}}>
sqloutheight<|||>3<|||>74
SessionManager_WindowHeight<|||>3<|||>470
MainWinLeft<|||>3<|||>814
MainWinTop<|||>3<|||>300
ColWidths_frmRoutineEditor.listParameters<|||>1<|||>50,410,90,70
ColsVisible_frmRoutineEditor.listParameters<|||>1<|||>0,1,2,3
ColPositions_frmRoutineEditor.listParameters<|||>1<|||>0,1,2,3
ColSort_frmRoutineEditor.listParameters<|||>1<|||>-1,0
querymemoheight<|||>3<|||>369
MemoEditorWidth<|||>3<|||>500
DateTimeEditor_CursorPos_Type4<|||>3<|||>11
CreateDbCollation<|||>1<|||>utf8mb4_general_ci
FileDialogEncoding_MainForm<|||>3<|||>0
FileDialogEncoding_loaddataform<|||>3<|||>0
loadfilename<|||>1<|||>D:\Documentos\Ingeniería de sistemas\Asignaturas\Lenguaje web l\programacion-web\productos.sql
CSVImportDuplicateHandling<|||>3<|||>1
ExportSQL_DataHow<|||>3<|||>4
SQLFile0<|||>1<|||>C:\Users\USUARIO\Desktop\compañerosporsimilitud.sql
SQLFile1<|||>1<|||>D:\Documentos\Ingeniería de sistemas\Asignaturas\Ingeniería de Software lll\companerosPorSimilitud.sql
SQLFile2<|||>1<|||>C:\xampps\htdocs\xampp\Pagina-Web\compañerosporsimilitud.sql
SQLFile3<|||>1<|||>D:\Documentos\Ingeniería de sistemas\Asignaturas\Lenguaje web l\programacion-web\productos.sql
SQLFile4<|||>1<|||>D:\Documentos\Ingeniería de sistemas\Asignaturas\Ingeniería de Software lll\compañerosPorSimilitud.sql
TabCloseOnDoubleClick<|||>3<|||>1
Servers\Unnamed\SessionCreated<|||>1<|||>2022-11-11 21:43:49
Servers\Unnamed\Host<|||>1<|||>127.0.0.1
Servers\Unnamed\WindowsAuth<|||>3<|||>0
Servers\Unnamed\CleartextPluginEnabled<|||>3<|||>0
Servers\Unnamed\User<|||>1<|||>root
Servers\Unnamed\Password<|||>1<|||>6
Servers\Unnamed\LoginPrompt<|||>3<|||>0
Servers\Unnamed\Port<|||>1<|||>3306
Servers\Unnamed\NetType<|||>3<|||>0
Servers\Unnamed\Compressed<|||>3<|||>0
Servers\Unnamed\LocalTimeZone<|||>3<|||>0
Servers\Unnamed\QueryTimeout<|||>3<|||>30
Servers\Unnamed\KeepAlive<|||>3<|||>20
Servers\Unnamed\FullTableStatus<|||>3<|||>1
Servers\Unnamed\Databases<|||>1<|||>
Servers\Unnamed\Library<|||>1<|||>libmariadb.dll
Servers\Unnamed\Comment<|||>1<|||>
Servers\Unnamed\StartupScriptFilename<|||>1<|||>
Servers\Unnamed\TreeBackground<|||>3<|||>536870911
Servers\Unnamed\SshExecutable<|||>1<|||>
Servers\Unnamed\SSHtunnelHost<|||>1<|||>
Servers\Unnamed\SSHtunnelHostPort<|||>3<|||>22
Servers\Unnamed\SSHtunnelUser<|||>1<|||>
Servers\Unnamed\SSHtunnelPassword<|||>1<|||>3
Servers\Unnamed\SSHtunnelTimeout<|||>3<|||>4
Servers\Unnamed\SSHtunnelPrivateKey<|||>1<|||>
Servers\Unnamed\SSHtunnelPort<|||>3<|||>3307
Servers\Unnamed\SSL_Active<|||>3<|||>0
Servers\Unnamed\SSL_Key<|||>1<|||>
Servers\Unnamed\SSL_Cert<|||>1<|||>
Servers\Unnamed\SSL_CA<|||>1<|||>
Servers\Unnamed\SSL_Cipher<|||>1<|||>
Servers\Unnamed\IgnoreDatabasePattern<|||>1<|||>
Servers\Unnamed\LogFileDdl<|||>3<|||>0
Servers\Unnamed\LogFileDml<|||>3<|||>0
Servers\Unnamed\LogFilePath<|||>1<|||>C:\Users\USUARIO\AppData\Roaming\HeidiSQL\Logs\%session\%db\%y%m%d.sql
Servers\Unnamed\ServerVersionFull<|||>1<|||>10.4.25-MariaDB - mariadb.org binary distribution
Servers\Unnamed\ConnectCount<|||>3<|||>1
Servers\Unnamed\ServerVersion<|||>3<|||>100425
Servers\Unnamed\LastConnect<|||>1<|||>2022-11-11 21:43:54
Servers\Unnamed\lastUsedDB<|||>1<|||>
